# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "e23-co2060-SkillShare"
remote_theme: cepdnaclk/eYY-project-theme
description: "Campus base skill sharing platform"
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
