spring.application.name=skillshare-backend

# --- Frontend Configuration ---
app.frontend.oauth2-redirect-url=http://localhost:5173/oauth2/redirect

# --- Database Configuration ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# --- Custom JWT Configuration ---
jwt.secret=${JWT_SECRET}

# Hibernate Configuration
# LOGIC: 'update' is great for development as it adds new columns automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Bot ON/OFF Switch
demo.bot.enabled=false
spring.config.import=optional:file:.env

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB