spring.application.name=skillshare-backend
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# --- Frontend Configuration ---
# Configured in profile specific files

# --- CORS Configuration ---
# Configured in profile specific files

# --- Database Configuration ---
spring.datasource.url=jdbc:postgresql://localhost:5432/skillshare
spring.datasource.username=postgres
spring.datasource.password=Sash4823

spring.security.oauth2.client.registration.github.client-id=Ov23liCa0eb91qge1zu1
spring.security.oauth2.client.registration.github.client-secret=e3c43d4d76b5a18d9acd1f037ddddffba3709d84
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# --- Custom JWT Configuration ---
jwt.secret=M2I0ZTU2Yjc4OWFiY2RlZjAxMjM0NTY3ODkwYWJjZGVmMDEyMzQ1Njc4OTBhYmNkZWYwMTIzNDU2Nzg5MGFiY2RlZg==
# Hibernate Configuration
# Configured in profile specific files

# Bot ON/OFF Switch
demo.bot.enabled=false
spring.config.import=optional:file:.env[.properties]

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Session Configuration
app.session.pending-response-timeout-hours=24
app.session.expiration.enabled=true