spring.application.name=skillshare-backend

# Database Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/skillshare
spring.datasource.username=postgres
spring.datasource.password=141456

# Hibernate Configuration
# LOGIC: 'update' is great for development as it adds new columns automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true